# Generated by Django 5.0.6 on 2024-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_remove_resultado_fecha_resultado_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='ventana_perdida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntaje',
            field=models.FloatField(),
        ),
    ]
