# Generated by Django 5.0.6 on 2024-06-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_resultado_ventana_perdida_alter_resultado_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('Sistema de numeración', 'Sistema de numeración')], max_length=100)),
                ('estado_correccion', models.CharField(default='pendiente', max_length=20)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('corregido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ventana_perdida', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estudiante')),
            ],
        ),
    ]
