# Generated by Django 5.0.6 on 2024-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_resultado_estado_correccion_alter_resultado_puntaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='actividad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='detalles',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='estado_correccion',
            field=models.CharField(default='pendiente', max_length=255),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntaje',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='ventana_perdida',
            field=models.IntegerField(default=0),
        ),
    ]
