# Generated by Django 5.0.6 on 2024-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_resultado_respuesta_alter_resultado_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='actividad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='estado_correccion',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='respuesta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
